import PorrigeImageBig from 'Assets/recipe-image-peanut-butter-porrige-640w.png';
import GrilledChickenWithSalsa from 'Assets/recipe-image-grilled-chicken-with-salsa-615w.png';
import MexicanCrepes from 'Assets/recipe-image-mexican-crepes-640w.png';
import FriedRiceWithChickenAndBroccoli from 'Assets/recipe-image-fried-rice-w-chicken-and-broccoli-640w.png';
import QuinoaWithBeans from 'Assets/recipe-image-quinoa-with-beans-640w.png';
import AppleCrumpets from 'Assets/recipe-image-apple-crumpets-640w.png';
import CocoaOmlette from 'Assets/recipe-image-cocoa-omlette-640w.png';
import ScrambledEggsAndAvocadoSandwich from 'Assets/recipe-image-scrambled-eggs-and-avocado-sandwich-640w.png';
import OmletteSandwich from 'Assets/recipe-image-omlette-sandwich-640w.png';
import FriedEggsSandwich from 'Assets/recipe-image-fried-egg-sandwich-640w.png';
import RaspberrySmoothie from 'Assets/recipe-image-raspberry-smoothie-640w.png';
import CarrotSmoothie from 'Assets/recipe-image-carrot-smoothie-640w.png';

const recipes = [
  {
    id: 1,
    name: 'Peanut Butter Porrige',
    macro: { calories: 554.6, protein: 39.2, carbs: 75.6, fats: 13.4 },
    image: PorrigeImageBig,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'low fat'],
    ingredients: [
      'porridge oats',
      'banana',
      'milk',
      'peanut butter',
      'skyr',
      'protein powder',
    ],
  },
  {
    id: 2,
    name: 'Grilled Chicken with Salsa',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    image: GrilledChickenWithSalsa,
    category: 'main courses',
    tags: ['gluten free', 'high protein', 'diary free', 'low fat'],
    ingredients: [
      'chicken',
      'poultry',
      'mango',
      'tomatoes',
      'rice',
      'red onion',
      'chilli',
      'avocado',
      'lemon',
      'coriander',
      'parsley',
      'garlic',
    ],
  },
  {
    id: 3,
    name: 'Mexican Crepes',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    image: MexicanCrepes,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
    ingredients: ['green bean', 'corn', 'beef', 'tomato paste', 'garlic'],
  },
  {
    id: 4,
    name: 'Fried Rice with Chicken and Broccoli',
    macro: { calories: 444.9, protein: 31.3, carbs: 65, fats: 9.6 },
    image: FriedRiceWithChickenAndBroccoli,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
    ingredients: [
      'chicken',
      'rice',
      'carrot',
      'broccoli',
      'garlic',
      'sesame seeds',
      'soy souce',
      'chilli',
      'ginger',
    ],
  },
  {
    id: 5,
    name: 'Quinoa with Beans',
    macro: { calories: 543.5, protein: 21.6, carbs: 80, fats: 18.6 },
    image: QuinoaWithBeans,
    category: 'main courses',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'diary free'],
    ingredients: [
      'quinoa',
      'red beans',
      'green beans',
      'avocado',
      'chilli',
      'onion',
      'cumin',
      'broth',
      'lime',
    ],
  },
  {
    id: 6,
    name: 'Apple Crumpets',
    macro: { calories: 501.7, protein: 15.7, carbs: 87.6, fats: 13.3 },
    image: AppleCrumpets,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'low fat'],
    ingredients: [
      'apple',
      'millet',
      'vanilla pudding',
      'coconut oil',
      'eggs',
      'yoghurt',
    ],
  },
  {
    id: 7,
    name: 'Cocoa Omelette',
    macro: { calories: 289.9, protein: 18.9, carbs: 19.4, fats: 15.1 },
    image: CocoaOmlette,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
    ingredients: ['eggs', 'oatmeal', 'cocoa', 'yoghurt', 'frozen fruits'],
  },
  {
    id: 8,
    name: 'Scrambled Eggs and Avocado Sandwich',
    macro: { calories: 424.3, protein: 17.3, carbs: 35.2, fats: 24.8 },
    image: ScrambledEggsAndAvocadoSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
    ingredients: [
      'eggs',
      'wholegrain bun',
      'butter',
      'avocado',
      'cherry tomatoes',
    ],
  },
  {
    id: 9,
    name: 'Omlette Sandwich',
    macro: { calories: 259.9, protein: 16.8, carbs: 2.7, fats: 19.9 },
    image: OmletteSandwich,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'high protein', 'keto'],
    ingredients: ['eggs', 'butter', 'cream cheese', 'parma ham', 'rucola'],
  },
  {
    id: 10,
    name: 'Fried Eggs Sandwich',
    macro: { calories: 429.3, protein: 20.3, carbs: 34.3, fats: 23.5 },
    image: FriedEggsSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein', 'keto'],
    ingredients: ['eggs', 'bread', 'rucola', 'cherry tomatoes'],
  },
  {
    id: 11,
    name: 'Raspberry Smoothie',
    macro: { calories: 392.8, protein: 31.2, carbs: 47.4, fats: 11.7 },
    image: RaspberrySmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'high protein', 'low fat'],
    ingredients: ['raspberries', 'milk', 'yoghurt', 'flaxseed'],
  },
  {
    id: 12,
    name: 'Carrot Smoothie',
    macro: { calories: 545.4, protein: 25, carbs: 101.7, fats: 8.1 },
    image: CarrotSmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'low fat'],
    ingredients: [
      'apple',
      'carrot',
      'honey',
      'orange',
      'pumpkin seeds',
      'yoghurt',
    ],
  },
  {
    id: 13,
    name: 'Peanut Butter Porrige',
    macro: { calories: 554.6, protein: 39.2, carbs: 75.6, fats: 13.4 },
    image: PorrigeImageBig,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'low fat'],
    ingredients: [
      'porridge oats',
      'banana',
      'milk',
      'peanut butter',
      'skyr',
      'protein powder',
    ],
  },
  {
    id: 14,
    name: 'Grilled Chicken with Salsa',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    image: GrilledChickenWithSalsa,
    category: 'main courses',
    tags: ['gluten free', 'high protein', 'diary free', 'low fat'],
    ingredients: [
      'chicken',
      'poultry',
      'mango',
      'tomatoes',
      'rice',
      'red onion',
      'chilli',
      'avocado',
      'lemon',
      'coriander',
      'parsley',
      'garlic',
    ],
  },
  {
    id: 15,
    name: 'Mexican Crepes',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    image: MexicanCrepes,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
    ingredients: ['green bean', 'corn', 'beef', 'tomato paste', 'garlic'],
  },
  {
    id: 16,
    name: 'Fried Rice with Chicken and Broccoli',
    macro: { calories: 444.9, protein: 31.3, carbs: 65, fats: 9.6 },
    image: FriedRiceWithChickenAndBroccoli,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
    ingredients: [
      'chicken',
      'rice',
      'carrot',
      'broccoli',
      'garlic',
      'sesame seeds',
      'soy souce',
      'chilli',
      'ginger',
    ],
  },
  {
    id: 17,
    name: 'Quinoa with Beans',
    macro: { calories: 543.5, protein: 21.6, carbs: 80, fats: 18.6 },
    image: QuinoaWithBeans,
    category: 'main courses',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'diary free'],
    ingredients: [
      'quinoa',
      'red beans',
      'green beans',
      'avocado',
      'chilli',
      'onion',
      'cumin',
      'broth',
      'lime',
    ],
  },
  {
    id: 18,
    name: 'Apple Crumpets',
    macro: { calories: 501.7, protein: 15.7, carbs: 87.6, fats: 13.3 },
    image: AppleCrumpets,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'low fat'],
    ingredients: [
      'apple',
      'millet',
      'vanilla pudding',
      'coconut oil',
      'eggs',
      'yoghurt',
    ],
  },
  {
    id: 19,
    name: 'Cocoa Omelette',
    macro: { calories: 289.9, protein: 18.9, carbs: 19.4, fats: 15.1 },
    image: CocoaOmlette,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
    ingredients: ['eggs', 'oatmeal', 'cocoa', 'yoghurt', 'frozen fruits'],
  },
  {
    id: 20,
    name: 'Scrambled Eggs and Avocado Sandwich',
    macro: { calories: 424.3, protein: 17.3, carbs: 35.2, fats: 24.8 },
    image: ScrambledEggsAndAvocadoSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
    ingredients: [
      'eggs',
      'wholegrain bun',
      'butter',
      'avocado',
      'cherry tomatoes',
    ],
  },
  {
    id: 21,
    name: 'Omlette Sandwich',
    macro: { calories: 259.9, protein: 16.8, carbs: 2.7, fats: 19.9 },
    image: OmletteSandwich,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'high protein', 'keto'],
    ingredients: ['eggs', 'butter', 'cream cheese', 'parma ham', 'rucola'],
  },
  {
    id: 22,
    name: 'Fried Eggs Sandwich',
    macro: { calories: 429.3, protein: 20.3, carbs: 34.3, fats: 23.5 },
    image: FriedEggsSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein', 'keto'],
    ingredients: ['eggs', 'bread', 'rucola', 'cherry tomatoes'],
  },
  {
    id: 23,
    name: 'Raspberry Smoothie',
    macro: { calories: 392.8, protein: 31.2, carbs: 47.4, fats: 11.7 },
    image: RaspberrySmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'high protein', 'low fat'],
    ingredients: ['raspberries', 'milk', 'yoghurt', 'flaxseed'],
  },
  {
    id: 24,
    name: 'Carrot Smoothie',
    macro: { calories: 545.4, protein: 25, carbs: 101.7, fats: 8.1 },
    image: CarrotSmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'low fat'],
    ingredients: [
      'apple',
      'carrot',
      'honey',
      'orange',
      'pumpkin seeds',
      'yoghurt',
    ],
  },
];

export default recipes;
