import PorrigeImageSmall from './assets/recipe-image-peanut-butter-porrige-105w.png';
import PorrigeImageBig from './assets/recipe-image-peanut-butter-porrige-640w.png';
import GrilledChickenWithSalsa from './assets/recipe-image-grilled-chicken-with-salsa-615w.png';
import MexicanCrepes from './assets/recipe-image-mexican-crepes-640w.png';
import FriedRiceWithChickenAndBroccoli from './assets/recipe-image-fried-rice-w-chicken-and-broccoli-640w.png';
import QuinoaWithBeans from './assets/recipe-image-quinoa-with-beans-640w.png';
import AppleCrumpets from './assets/recipe-image-apple-crumpets-640w.png';
import CocoaOmlette from './assets/recipe-image-cocoa-omlette-640w.png';
import ScrambledEggsAndAvocadoSandwich from './assets/recipe-image-scrambled-eggs-and-avocado-sandwich-640w.png';
import OmletteSandwich from './assets/recipe-image-omlette-sandwich-640w.png';
import FriedEggsSandwich from './assets/recipe-image-fried-egg-sandwich-640w.png';
import RaspberrySmoothie from './assets/recipe-image-raspberry-smoothie-640w.png';
import CarrotSmoothie from './assets/recipe-image-carrot-smoothie-640w.png';

const recipes = [
  {
    id: 1,
    name: 'Peanut Butter Porrige',
    macro: { calories: 554.6, protein: 39.2, carbs: 75.6, fats: 13.4 },
    imageMobile: PorrigeImageSmall,
    imageDesktop: PorrigeImageBig,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'low fat'],
  },
  {
    id: 2,
    name: 'Grilled Chicken with Salsa',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    imageMobile: GrilledChickenWithSalsa,
    imageDesktop: GrilledChickenWithSalsa,
    category: 'main courses',
    tags: ['gluten free', 'high protein', 'diary free', 'low fat'],
  },
  {
    id: 3,
    name: 'Mexican Crepes',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    imageMobile: MexicanCrepes,
    imageDesktop: MexicanCrepes,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
  },
  {
    id: 4,
    name: 'Fried Rice with Chicken and Broccoli',
    macro: { calories: 444.9, protein: 31.3, carbs: 65, fats: 9.6 },
    imageMobile: FriedRiceWithChickenAndBroccoli,
    imageDesktop: FriedRiceWithChickenAndBroccoli,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
  },
  {
    id: 5,
    name: 'Quinoa with Beans',
    macro: { calories: 543.5, protein: 21.6, carbs: 80, fats: 18.6 },
    imageMobile: QuinoaWithBeans,
    imageDesktop: QuinoaWithBeans,
    category: 'main courses',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'diary free'],
  },
  {
    id: 6,
    name: 'Apple Crumpets',
    macro: { calories: 501.7, protein: 15.7, carbs: 87.6, fats: 13.3 },
    imageMobile: AppleCrumpets,
    imageDesktop: AppleCrumpets,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'low fat'],
  },
  {
    id: 7,
    name: 'Cocoa Omelette',
    macro: { calories: 289.9, protein: 18.9, carbs: 19.4, fats: 15.1 },
    imageMobile: CocoaOmlette,
    imageDesktop: CocoaOmlette,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
  },
  {
    id: 8,
    name: 'Scrambled Eggs and Avocado Sandwich',
    macro: { calories: 424.3, protein: 17.3, carbs: 35.2, fats: 24.8 },
    imageMobile: ScrambledEggsAndAvocadoSandwich,
    imageDesktop: ScrambledEggsAndAvocadoSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
  },
  {
    id: 9,
    name: 'Omlette Sandwich',
    macro: { calories: 259.9, protein: 16.8, carbs: 2.7, fats: 19.9 },
    imageMobile: OmletteSandwich,
    imageDesktop: OmletteSandwich,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'high protein', 'keto'],
  },
  {
    id: 10,
    name: 'Fried Eggs Sandwich',
    macro: { calories: 429.3, protein: 20.3, carbs: 34.3, fats: 23.5 },
    imageMobile: FriedEggsSandwich,
    imageDesktop: FriedEggsSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein', 'keto'],
  },
  {
    id: 11,
    name: 'Raspberry Smoothie',
    macro: { calories: 392.8, protein: 31.2, carbs: 47.4, fats: 11.7 },
    imageMobile: RaspberrySmoothie,
    imageDesktop: RaspberrySmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'high protein', 'low fat'],
  },
  {
    id: 12,
    name: 'Carrot Smoothie',
    macro: { calories: 545.4, protein: 25, carbs: 101.7, fats: 8.1 },
    imageMobile: CarrotSmoothie,
    imageDesktop: CarrotSmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'low fat'],
  },
  {
    id: 13,
    name: 'Peanut Butter Porrige',
    macro: { calories: 554.6, protein: 39.2, carbs: 75.6, fats: 13.4 },
    imageMobile: PorrigeImageSmall,
    imageDesktop: PorrigeImageBig,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'low fat'],
  },
  {
    id: 14,
    name: 'Grilled Chicken with Salsa',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    imageMobile: GrilledChickenWithSalsa,
    imageDesktop: GrilledChickenWithSalsa,
    category: 'main courses',
    tags: ['gluten free', 'high protein', 'diary free', 'low fat'],
  },
  {
    id: 15,
    name: 'Mexican Crepes',
    macro: { calories: 428.7, protein: 26.3, carbs: 61.9, fats: 9.6 },
    imageMobile: MexicanCrepes,
    imageDesktop: MexicanCrepes,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
  },
  {
    id: 16,
    name: 'Fried Rice with Chicken and Broccoli',
    macro: { calories: 444.9, protein: 31.3, carbs: 65, fats: 9.6 },
    imageMobile: FriedRiceWithChickenAndBroccoli,
    imageDesktop: FriedRiceWithChickenAndBroccoli,
    category: 'main courses',
    tags: ['high protein', 'diary free'],
  },
  {
    id: 17,
    name: 'Quinoa with Beans',
    macro: { calories: 543.5, protein: 21.6, carbs: 80, fats: 18.6 },
    imageMobile: QuinoaWithBeans,
    imageDesktop: QuinoaWithBeans,
    category: 'main courses',
    tags: ['gluten free', 'vegetarian', 'vegan', 'high protein', 'diary free'],
  },
  {
    id: 18,
    name: 'Apple Crumpets',
    macro: { calories: 501.7, protein: 15.7, carbs: 87.6, fats: 13.3 },
    imageMobile: AppleCrumpets,
    imageDesktop: AppleCrumpets,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'vegetarian', 'low fat'],
  },
  {
    id: 19,
    name: 'Cocoa Omelette',
    macro: { calories: 289.9, protein: 18.9, carbs: 19.4, fats: 15.1 },
    imageMobile: CocoaOmlette,
    imageDesktop: CocoaOmlette,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
  },
  {
    id: 20,
    name: 'Scrambled Eggs and Avocado Sandwich',
    macro: { calories: 424.3, protein: 17.3, carbs: 35.2, fats: 24.8 },
    imageMobile: ScrambledEggsAndAvocadoSandwich,
    imageDesktop: ScrambledEggsAndAvocadoSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein'],
  },
  {
    id: 21,
    name: 'Omlette Sandwich',
    macro: { calories: 259.9, protein: 16.8, carbs: 2.7, fats: 19.9 },
    imageMobile: OmletteSandwich,
    imageDesktop: OmletteSandwich,
    category: 'breakfasts and suppers',
    tags: ['gluten free', 'high protein', 'keto'],
  },
  {
    id: 22,
    name: 'Fried Eggs Sandwich',
    macro: { calories: 429.3, protein: 20.3, carbs: 34.3, fats: 23.5 },
    imageMobile: FriedEggsSandwich,
    imageDesktop: FriedEggsSandwich,
    category: 'breakfasts and suppers',
    tags: ['vegetarian', 'high protein', 'keto'],
  },
  {
    id: 23,
    name: 'Raspberry Smoothie',
    macro: { calories: 392.8, protein: 31.2, carbs: 47.4, fats: 11.7 },
    imageMobile: RaspberrySmoothie,
    imageDesktop: RaspberrySmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'high protein', 'low fat'],
  },
  {
    id: 24,
    name: 'Carrot Smoothie',
    macro: { calories: 545.4, protein: 25, carbs: 101.7, fats: 8.1 },
    imageMobile: CarrotSmoothie,
    imageDesktop: CarrotSmoothie,
    category: 'smoothies',
    tags: ['gluten free', 'vegetarian', 'low fat'],
  },
];

export default recipes;
